nl-design-system/terraform

gebruikersonderzoeken.tf
=> fix: typo in required_status_checks

.github/dependabot.yml, .github/workflows/terraform.yml
- Keep GitHub Actions up to date
- Use the latest `actions/checkout`
=> ci: add dependabot

.github/CODEOWNERS, terraform.tf
... require kernteam-admin to merge them.
=> ci: allow community maintainers to make PRs

.terraform.lock.hcl, gebruikersonderzoeken.tf, team-members.tf
- add gebruikersonderzoeken to team-members
- add jeroenduc as team member
=> ci: add jeroenduc to gebruikersonderzoeken

rvo.tf, team-members.tf, user.tf
Run: https://app.terraform.io/app/nl-design-system/workspaces/github/runs/run-ghoh9SjNS5Ztw6xr
=> feat: add rvo

example.tf
Enable Secret Scanning and Secret Scanning Push Protection
=> feat: enable security_and_analysis for example

team-members.tf
Only reshuffled the names so a PR is possible
=> fix: rvo-committer

gebruikersonderzoeken.tf
This was changed in the GitHub UI before
=> feat: change gebruikersonderzoeken build_type

documentatie.tf
Deploy documenatie to GitHub Pages using the workflow build_type instead of legacy
=> refactor: update documentatie pages config

example.tf
Change the build_type to workflow for the example repository
=> chore: change GH Pages for example

README.md, providers.tf, variables.tf
- Move variables into variables.tf
- Use a Terraform input variable for GITHUB_TOKEN instead of an environment variable
- Update README.md:
- update documention for running terraform locally to import repositories
- update resources and data sources to include what we use
=> chore: clean up files

team-members.tf, team.tf, themes.tf, user.tf
Dawad gaat meehelpen, en Francesca wil vanuit VNG vast ook bijdragen
=> chore: create Voorbeeld Theme team

rijkshuisstijl-community.tf
=> build(rijkshuisstijl-community): added vercel deployment for template page

team-members.tf, user.tf
Joeri, Gerwin en Sjimmie verwijderd als committers, zij zijn op het moment bezig met andere projecten.
=> Removed Quintor team-members

candidate.tf
Change the actor_type for nl-design-system-ci to Team from RepositoryRole
=> chore: change actor_type to Team

team-members.tf, user.tf
Adds Tom Jonkman to the rvo team as a committer
=> chore: add tom-jonkman to rvo

.gitignore, team-members.tf
Update kernteam committers team
- Removed: `bddjong`
=> chore: remove self from kernteam committers

team-members.tf, team.tf, themes.tf, user.tf
- add user RGRMdesign
- add github_team nora
- add github_team nora-committer
- allow nora-committer to push to themes
=> chore: add RGRMdesign to themes repo

basis.tf
This is where the basis theme and eslint/stylelint/style-dictionary basis configs can go.
We won't need a Vercel deploy I think, because it will not have a Storybook.
=> feat: add basis repo

team-members.tf
Give Rico access to work on Mendix stuff.
=> chore: give Rico write access for Rotterdam

team-members.tf, user.tf
closes https://github.com/nl-design-system/rijkshuisstijl-community/issues/1041
=> chore: removed Ruben O from team and added Roy as extra maintainer

team-members.tf, user.tf
- Remove MrSkippy
- Add edblocker
- Add dineshduggal
=> chore: update logius-committers

team-members.tf, user.tf
Update user.tf and team-members.tf with RosanneBakker for Logius
Graag haar ook aan **Chromatic** toevoegen als _Reviewer_
=> Update user.tf with RosanneBakker

wcag-statistieken.tf
The existing repostiory was imported. This commit adds the repo as code and updates some settings.
=> feat: add wcag-statistieken

team-members.tf
Robbert and Yolijn need to be "maintainer"
=> fix: add explicit maintainer roles

documentatie.tf
Give "expertteam digitale toegankelijkheid" committer access to the documentatie repository
=> feat: update documentatie collaborators

team-members.tf, user.tf
Use the correct GitHub username
=> fix: username

team-members.tf
Add eslook to kernteam-maintainer
=> fix: update terraform collaborators

tilburg.tf
Replace `github_branch_protection` with a `github_repository_ruleset` for branch protecting the `main` branch.
Remove legacy branch protection for `gh-pages` and switch the GitHub Pages `build_type` to `"workflow"`.
=> refactor: switch to ruleset for "tilburg"

overheidsbrede-portalen-community.tf
The new name is overheidsbrede-portalen-community
=> chore: rename services

team-members.tf, user.tf
https://github.com/nl-design-system/rijkshuisstijl-community/issues/1214
=> chore: removed Roy as team member, removed Mees as maintainer and added Adham as maintainer

team-members.tf, user.tf
=> chore: add RenateRoke

overheidsbrede-portalen-community.tf
=> chore: switch "overheidsbrede-portalen-community" to ruleset

dot-github.tf
- Remove github_branch_protection
Closes #214
=> chore: switch ".github" repo to ruleset

gebruikersonderzoeken.tf
- Remove github_branch_protection for main and gh-pages
Closes #216
=> chore: switch "gebruikersonderzoeken" to ruleset

icons.tf
- Remove github_branch_protection
Closes #217
=> chore: switch "icons" to ruleset

index.tf
- Remove github_branch_protection
Closes #218
=> chore: switch "index" to ruleset

themes.tf
- Add missing bypass_actors
- Add the correct required_check
=> fix: themes repo ruleset

backlog.tf
- Remove github_branch_protection
Closes #211
=> refactor: switch "backlog" to ruleset

example-with-next-js.tf
Prepare the example-with-next-js repo for archiving
=> chore: prepare for archiving

backlog.tf, basis.tf, candidate.tf, denhaag.tf, documentatie.tf, example-with-angular.tf, example.tf, hall-of-fame.tf_, lux.tf, matomo.tf, mendix.tf, nldesignsystem-nl-storybook.tf, nlds-community-blocks.tf, nlds-gravity-forms.tf, publiccode-parser-action.tf, rijkshuisstijl-community.tf, rotterdam.tf, rvo.tf, theme-builder.tf, tilburg.tf, tiptap.tf, utrecht.tf, wcag-statistieken.tf
- Add bypass_actors where they were missing
- Keep the same order in the "github_repository_ruleset" blocks  so it's easier to spot if something is different
- Use "default-branch-protection" instead of "main"
- Add "github_branch_default" for all repositories that did not have it yet
=> chore: align rulesets

theme-builder.tf
The repository should be initialised first
=> fix: comment out default branch for theme-builder

documentatie.tf
- Add github_repository_ruleset for the default branch
- Add github_repository_ruleset for gh-pages, assets, and storybook
- Remove classic github_branch_protection
Closes #213
=> chore: switch "documentatie" to rulesets

lux.tf
- Add "github_repository_ruleset" for the `~DEFAULT_BRANCH` branch
- Add "github_repository_ruleset" for the `gh-pages` branch
Closes #219
=> chore: switch "lux" to rulesets

matomo.tf
- Add "github_repository_ruleset" for the default branch
=> chore: switch "matomo" to rulesets

nldesignsystem-nl-storybook.tf
- Add "github_repository_ruleset" for the default branch
- Add "github_repository_ruleset" for the `gh-pages` branch
- Remove "github_branch_protection"s
Closes #221
=> chore: switch "nldesignsystem-nl-storybook" to rulesets

.husky/pre-commit
- Make sure the pre-commit hook only runs on changed files that were added to the index
- Also allow for partially staged files
=> chore: improve pre-commit hook

nlds-gravity-forms.tf
- Add "github_repository_ruleset" for default branch
=> chore: switch "nlds-gravity-forms" to rulesets

nlds-community-blocks.tf
- Add "github_repository_ruleset" for main branch
Closes #222
=> chore: switch "nlds-community-blocks" to rulesets

publiccode-parser-action.tf
- Add "github_repository_ruleset" for the default branch
Closes #224
=> chore: switch "publiccode-parser-action" to rulesets

rijkshuisstijl-community.tf
- Add "github_repository_ruleset" for the main branch
- Add "github_repository_ruleset" for the main branch for push protection only
- Add "github_repository_ruleset" for the `gh-pages` branch
Closes #225
=> chore: switch "rijkshuisstijl-community" to ruleset

rotterdam.tf
- Add "github_repository_ruleset" for the default branch and `gh-pages`
=> chore: switch "rotterdam" to rulesets

rvo.tf
- Add "github_repository_ruleset"s for default and `gh-pages` branches
=> chore: switch "rvo" to rulesets

denhaag.tf
- Add "github_repository_ruleset" for the `www.denhaag.nl` branch and the default branch
- Add "github_repository_ruleset" for the `gh-pages` branch
- Remove "github_branch_protection"s
Closes #212
=> chore: switch "denhaag" to rulesets

terraform.tf
Replace the legacy branch protection in the "terraform" repository with a new ruleset based branch protection.
=> feat: add a branch ruleset for "terraform" repo

architectuur.tf, github_organization.tf
=> feat: allow GitHub Actions per repo

architectuur.tf, github_organization.tf
This reverts commit 20a9422686fe322cf1602aaa2fc6753a884b66f0.
=> Revert "feat: allow GitHub Actions per repo"

team-members.tf, team.tf, terraform.tf, user.tf
- Add new users
- Add new team
- Give new team push access to terraform
=> chore: add gemeente-den-haag-maintainer team

candidate.tf
Configure the node_version using the vercel_project resource
=> chore: add node_version to vercel_project

team-members.tf, user.tf
=> chore: add Laurence to DITP team

terraform.tf
- enable secret scanning
- enable secret scanning push protection
=> chore: enable advanced security

team-members.tf, user.tf
Add new user rnieuwerf to team LUX
=> Add user RNieuwerf

rijkshuisstijl-community.tf
Closes: nl-design-system/rijkshuisstijl-community#1480
=> feat: Ondersteunen van Angular Storybook in Vercel (nl-design-system/rijkshuisstijl-community#1480)

rijkshuisstijl-community.tf, vercel_team_config.tf
Add vercel_team_config so this can be used in the vercel_project resources
=> fix: add vercel_team_config

example-with-angular.tf
- Switch to workflow based GH Pages
- Use a repository ruleset instead of the classic branch protection.
=> chore: update example-with-angular

team-members.tf, utrecht.tf
Add community-committers to Utrecht collaborators
Make dineshduggal a member of community-committers
=> chore: update utrecht collaborators

team-members.tf, user.tf
=> chore: add Franka

gebruikersonderzoeken.tf
Duplicate of #375 but now not as a fork
=> Add vercel preview deployment for new gebruikersonderzoeken website

gebruikersonderzoeken.tf
Voor: https://github.com/orgs/nl-design-system/projects/79
=> chore: enable projects for gebruikersonderzoeken

matomo.tf, nlds-gravity-forms.tf, publiccode-parser-action.tf, tiptap.tf
Add `archive_on_destroy` for:
- matomo
- nlds-gravity-forms
- publiccode-parser-action
- tiptap
=> chore: prepare repos for archiving

mijn-services.tf
Prevent churn by resetting this to `gh-pages`.
=> fix: update mijn-services pages

gebruikersonderzoeken.tf
Turn on Secret Scanning and Secret Scanning Push Protection for the gebruikersonderzoeken repository.
=> feat: update gebruikersonderzoeken

team-members.tf, user.tf
=> chore: add new user

.github/ISSUE_TEMPLATE/new-user.md
Issue template toegevoegd voor nieuwe gebruiker issue afvinklijstje.
=> docs: add new user issue template

team-members.tf, user.tf
=> chore: remove user

theme-wizard.tf
refs https://github.com/nl-design-system/theme-wizard/pull/38
=> chore: configure theme-wizard-server vercel project
