nl-design-system/terraform

lux.tf, team-members.tf, team.tf
GitHub suggereert dat we nested teams moeten gebruiken voor meer privileges: [About teams: Preparing to nest teams in your organization](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#preparing-to-nest-teams-in-your-organization):
> At the top of the team hierarchy, you should give parent teams repository access permissions that are safe for every member of the parent team and its child teams. As you move toward the bottom of the hierarchy, you can grant child teams additional, more granular access to more sensitive repositories.
Misschien lost dit ook het probleem op van de notifications die we steeds krijgen door "conflicting roles".
Dus nu is het idee:
- `committer`: push rechten
- `maintainer` 1 of meer committers zijn ook maintainer
=> chore: add `maintainer` nested team for Logius

team-members.tf, team.tf, terraform.tf, user.tf
Having the maintainer available first allows us to let the maintainer review the first batch of team members.
=> feat: add RVO maintainer team ahead of RVO repo config

team-members.tf, team.tf
- `kernteam`: iedereen
- `kernteam-triage`: rechten voor issues maken enzo
- `kernteam-committer`: rechten voor commits doen voor pull requests alle nl-design-system repositories
- `kernteam-maintainer`: rechten voor repositories beheren
=> refactor: use nested teems to avoid conflicting roles

team-members.tf, user.tf
Make owners maintainers instead of members to prevent:
> Attempting to set a user who is an organization owner to "member" will
result in the user being granted "maintainer" instead; this can result in a perpetual `terraform plan` diff that changes their status back to "member".
=> fix: username casing

.github/workflows/terraform.yml, team-members.tf, terraform.tf
Switch the current setup of using GitHub Actions for Terraform "plan" and "apply" runs to using the official Terraform Cloud app for GitHub.
Replace the old starter action with a "Terraform format check" that only checks if `terraform fmt` was run locally.
In a subsequent pull request the "Terraform format check" check will be added to the "terraform-main" `github_branch_protection`.
=> build: switch to Terraform Cloud app on GitHub

team.tf
Fixes:
```txt
│ Error: POST https://api.github.com/orgs/nl-design-system/teams: 422 Validation Failed [{Resource:Team Field:data Code:unprocessable Message:Name must be unique for this org}]
│ 
│   with github_team.vng-services-committer,
│   on team.tf line 351, in resource "github_team" "vng-services-committer":
│  351: resource "github_team" "vng-services-committer" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```
=> fix: duplicate team name

team-members.tf
Re-order the names only to make a PR possible
=> fix: kernteam-committer team

documentatie.tf
Changes to the "assets" branch do not result in builds by Vercel as configured in `vercel.json` on the "main" branch of the documentatie repository.
PRs *to* the "assets" branch however _do_ result in builds though and those builds will always fail because there is nothing to build on the "assets" branch.
=> feat: remove PR reviews for assets branch

documentatie.tf
Make sure it is no longer possible to accidentally push directly to the `main` branch for admins
=> feat: improve documentatie branch protection

documentatie.tf
Enforcing admins includes enforcing this for the bot user that needs to be able to commit from a GitHub Action
=> chore: update documentatie branch protection

example.tf
This should fix this error:
> Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the nl-design-system/example repository.
=> chore: add missing kernteam-dependabot

.editorconfig, .github/dependabot.yml
Let Dependabot update terraform dependencies monthly.
Remove "timezone" and "time" from "schedule" because they don't do anything for "monthly" intervals.
Add missing `.editorconfig`.
=> build: add terraform to dependabot config

terraform.tf
This allows Dependabot to assign the kernteam-dependabot members as reviewers for the PR.
=> chore: add kernteam-dependabot to terraform repo

providers.tf
VERCEL_API_TOKEN was set as a Terraform input variable instead of an environment variable.
=> fix: add missing variable

tilburg.tf
@hansregeer merkte op dat er een wachtwoord nodig is om de preview deployment te bekijken, hiermee is dat niet meer nodig.
=> ci: do not require authentication to access Vercel deployments

rijkshuisstijl-community.tf
Give kernteam-committer and logius-committer push allowance
=> fix: rijkshuisstijl-community merge rights

candidate.tf
For now, remove the bypass_actor from the ruleset to protect the main branch of the candidate repo.
The plan is to get the ruleset in place and then manually add the bypass actor and import that using terraform on the command line.
=> fix: remove bypass_actor from ruleset 

candidate.tf, team-members.tf, team.tf
Add kernteam-ci as a team with one member (nl-design-system-ci) that is allowed to bypass branch protections on the main branch in the candidate repository.
=> chore: add kernteam-ci

team-members.tf
=> fix: maintainer role

gebruikersonderzoeken.tf
Add `kernteam-dependabot` as a collaborator on the gebruikersonderzoeken repository so Dependabot can request reviews instead of complaining that it cannot.
=> chore: gebruikersonderzoeken collaborators

documentatie.tf
Add `kernteam-dependabot` as a collaborator on the documentatie repository so Dependabot can request reviews instead of complaining that it cannot.
=> chore: documentatie collaborators

team-members.tf, user.tf
Martijn den Held is de nieuwe Scrum Master van LUX. Toegevoegd aan `triage` zodat hij ook in ons board en issues kan.
=> Update team-members.tf with MdenHeld for Logius/Lux

rijkshuisstijl-community.tf
Change suggested by @JoeriRoijenga
=> chore(rijkshuisstijl-community): added test-a11y as required status check

providers.tf
@Robbert @Yolijn ik draai lokaal terraform `1.10.4` en heb de setting in Terraform cloud ook aangepast. Jullie zullen dat ook even moeten doen.
=> chore: bump terraform required_version

backlog.tf, basis.tf, candidate.tf, denhaag.tf, documentatie.tf, dot-github.tf, example-with-angular.tf, example-with-next-js.tf, example.tf, gebruikersonderzoeken.tf, icons.tf, index.tf, lux.tf, matomo.tf, mendix.tf, nldesignsystem-nl-storybook.tf, nlds-community-blocks.tf, nlds-gravity-forms.tf, publiccode-parser-action.tf, rijkshuisstijl-community.tf, rotterdam.tf, rvo.tf, services.tf, terraform.tf, themes.tf, tilburg.tf, tiptap.tf, utrecht.tf
For github_repository_collaborators team blocks, use the id instead of the slug
=> fix: use team id instead of slug

basis.tf, candidate.tf, example.tf, gebruikersonderzoeken.tf, mendix.tf, tiptap.tf, utrecht.tf
Prevent unnecessary "changes" by adding the "source" block that GitHub keeps around invisibly in the background.
See this example from an API call to the pages endpoint of the candidate repository. `"source"` is still present even though `"build_type"` is set to `"workflow"`.
```json
{
"url":
"https://api.github.com/repos/nl-design-system/candidate/pages",
"status": null,
"cname": null,
"custom_404": false,
"html_url": "https://nl-design-system.github.io/candidate/",
"build_type": "workflow",
"source": {
"branch": "main",
"path": "/"
},
"public": true,
"protected_domain_state": null,
"pending_domain_unverified_at": null,
"https_enforced": true
}
```
=> fix: reduce churn

gebruikersonderzoeken.tf
The GitHub REST API shows the following for the GH Pages configuration:
```json
"source": {
"branch": "gh-pages",
"path": "/"
}
```
To reduce churn, we'll match that here even though it does not really make sense since we use GitHub Actions as the source instead of deploying from a branch.
=> chore: gebruikersonderzoeken gh-pages

themes.tf
Mijn aanname is dat alle Quintor committers toegang krijgen. Klopt dit?
=> chore: allow Quintor committers to push to themes

candidate.tf
After this run, there should ideally no longer be a GitHub Pages setup for the Candidate repo.
We'll re-add it without the `source` block to see if that gets rid of churn permanently.
=> chore: remove Candidate GitHub Pages config

candidate.tf
Re-add the Candidate pages block, but now without a `source` block
=> chore: re-add Candidate pages

candidate.tf
Re-add the `source` block for pages in the "candidate" repo to prevent churn
=> chore: prevent churn

index.tf
Allow the "kernteam-dependabot" team to triage the "index" repository.
=> chore: add kernteam-dependabot to "index" repo

example.tf
=> chore: switch to ruleset for "example"

themes.tf
Switch to using the GitHub Actions based workflow instead of the legacy `gh-pages` branch based workflow.
Remove branch protection for the `gh-pages` branch.
=> chore: update GitHub Pages "themes" configuration

themes.tf
- Add an explicit default branch "main"
- Add a ruleset to protect the default branch
- Remove the legacy branch protections for `gh-pages` and `main`
Closes #230
=> refactor: switch to ruleset for "themes"

denhaag.tf
Merel had toch nog geen merge rechten, dit fixt 't denk ik
=> chore: allow Acato committer team to merge into `www.denhaag.nl` branch

denhaag.tf
The "denhaag" repository was not created using "example" as a template so trying to add a `template` block causes churn.
=> fix: denhaag churn

documentatie.tf
simply using branch names does not work. For the main branch we used refs/heads/main, so use that for these branches as well.
=> fix: include patterns

backlog.tf, basis.tf, candidate.tf, denhaag.tf, documentatie.tf, dot-github.tf, example.tf, gebruikersonderzoeken.tf, hall-of-fame.tf_, icons.tf, index.tf, lux.tf, matomo.tf, mendix.tf, nldesignsystem-nl-storybook.tf, nlds-community-blocks.tf, nlds-gravity-forms.tf, overheidsbrede-portalen-community.tf, publiccode-parser-action.tf, rijkshuisstijl-community.tf, rotterdam.tf, theme-builder.tf, themes.tf, tilburg.tf, tiptap.tf, utrecht.tf, wcag-statistieken.tf
- Set rules.creation to false; branches have already been created and need no protection from being created.
- Remove do_not_enforce_on_create = false from required_status_checks as it's always set to the default `false` and it's irrelevant for existing branches
- Add missing strict_required_status_checks_policy where needed and set it to `true` in "basis" and "candidate"
=> Clean up rulesets

rvo.tf
Allow rvo-maintainer to bypass the ruleset
=> chore: update rvo bypass actors

architectuur.tf
Een nieuwe repo voor archimate-bestanden en GitHub Pages om ze in HTML te laten zien.
- gekopieerd van `basis`
- expertteam toegevoegd met push-rechten
- required checks uitgezet, in eerste instantie is er nog geen npm-setup
- required review uitgezet, omdat dit voornamelijk solitair werk is en geen risico voor productie-omgevingen heeft
- Nederlandstalig omdat de architectuur-documentatie volledig Nederlands is
=> feat: add architectuur repo

github_organization.tf
Restrict the use of GitHub Actions to the ones that are currently in use
=> feat: restrict allowed github actions

candidate.tf
Make the changeset-status check a required check for the candidate repository.
This will make sure that Dependabot pull requests cannot be merged because they will always lack a changeset.
For `dependabot/npm_and_yarn/*` PRs this is desirable because they should not be merged.
For `dependabot/github_actions/*` PRs this means that an empty changeset will have to be added before they can be merged.
=> chore: add changeset-status check

gebruikersonderzoeken.tf
The `name` keys were removed so just use the lowercase names of the actual jobs.
=> fix: checks for gebruikersonderzoeken

.husky/pre-commit
Make sure to exit immediately if there were no staged files. This makes sure that `git commit --amend` still works.
Add comments to clarify what's happening.
=> chore: improve pre-commit hook

docs/adding-users.md
Add documentation for adding users to the NL Design System organisation and existing teams.
In the pas this has gone wrong for various reasons:
- opening 2 PRs, 1 to add a user and 1 to add the user to a team (fails)
- using incorrect casing which will result in a lot of Terraform churn
Hopefully this will prevent these kinds of mistakes.
=> docs: adding users

gebruikersonderzoeken.tf
Now that gebruikersonderzoeken-next is working, it missed its correct build command
=> Update build command for gebruikersonderzoeken next

gebruikersonderzoeken.tf
Om een vercel.json file te kunnen gebruiken in packages/website/ in de gebruikersonderzoeken repo, de vercel project root moet gezet zijn, anders wordt er alleen gekeken naar de vercel.json file in de root van de repo en niet dieper
=> Set root directory for gebruikersonderzoeken-next

gebruikersonderzoeken.tf
Explicitly set `enable_affected_projects_deployments` to `false` as a workaround for what seems like a bug [1] in the provider.
[1]: https://github.com/vercel/terraform-provider-vercel/issues/296
=> fix: gebruikersonderzoeken

team-members.tf, user.tf
Alvast voor maandag 11 augustus: voeg Roy toe als kernteam committer, triage etc.
=> chore: add Roy to kernteam

github_organization.tf
Nodig voor https://github.com/nl-design-system/utrecht/pull/2875 voor de SBoM die in de ICTU Kwaliteitsaanpak staat.
=> ci: allow anchore/sbom-action in GitHub Actions

README.md, team-members.tf, team.tf, user.tf, utrecht.tf
Op verzoek van Utrecht kernteam, toevoegen van nieuw team lid om te kunnen pushen naar een branch. Voor consistentie ook ontbrekende utrecht teams aangemaakt (maintainer, committer, triage)
Daarnaast op verzoek van zowel Utrecht kernteam als @Robbert documentatie toegevoegd aan `README.md` over de structuur van permissions.
=> chore: add utrecht committer and maintainer teams and add pixelgitter user

terraform.tf
Disable the auto-merge option in the `terraform` repository. This should make merging feel more like a deliberate "merge now" action.
=> chore: update terraform repo

utrecht.tf
Make sure that `github_team.gemeente-utrecht-triage` only has triage permission.
Make sure that `github_team.gemeente-utrecht-committer` only has push permission.
Change the order of the collaborators to align with how teams descend from one another.
Because the `github_team.gemeente-utrecht` team was still part of `github_repository_collaborators.utrecht` and both `github_team.gemeente-utrecht-triage` and `github_team.gemeente-utrecht-committer` were descendant teams of `github_team.gemeente-utrecht`, they inherited the maintain permission instead of having their correct permission.
This resulted in all subsequent runs unsuccesfully trying to change the permission to what it should be again without an actual error.
=> fix: update utrecht collaborators

CODE_OF_CONDUCT.md, CODE_OF_CONDUCT.nl.md
Make the Code of Conduct for this repository explicit in the repository instead of relying on the Code of Conduct that lives in https://github.com/nl-design-system/.github
=> docs: add missing code of conduct files

editor.tf, team-members.tf, team.tf, theme-builder.tf, theme-wizard.tf
Doel:
- maintainer team toevoegen voor expertteam voor maintainer rechten in GitHub, zodat deze mensen Project boards kunnen aanpassen en GitHub Milestones en Labels kunnen bewerken
- blijkbaar was er al een theme-builder repo, die kan weg nu we theme-wizard hebben
- de teamsamenstelling was anders eerder dit jaar, alleen de huidige teamleden hoeven rechten te hebben. De verwijderde mensen hebben alsnog veel rechten doordat ze in het kernteam zitten.
- Extra branch deploy omdat er meerdere dingen in theme-wizard zitten: de website en storybook
=> chore: expertteam tweaks
